import type { AppData } from "./types";

export const demoData: AppData = {
  stores: ["西湖店", "滨江店", "钱江新城店", "城西店"],
  template: {
    id: "daily-standard",
    name: "门店经营日报 · 标准版",
    description: "适合日常经营、微信群报账和运营复盘的统一模板",
    updatedAt: "2026-09-28 18:40",
    fields: [
      { id: "revenue", label: "实收金额", group: "经营数据", required: true, enabled: true, copyToWechat: true },
      { id: "traffic", label: "客流", group: "经营数据", required: true, enabled: true, copyToWechat: true },
      { id: "avgTicket", label: "客单价", group: "经营数据", required: false, enabled: true, copyToWechat: true },
      { id: "wasteAmount", label: "报损金额", group: "经营数据", required: false, enabled: true, copyToWechat: true },
      { id: "todayDone", label: "今日完成", group: "现场记录", required: true, enabled: true, copyToWechat: true },
      { id: "tomorrowPlan", label: "明日计划", group: "现场记录", required: true, enabled: true, copyToWechat: true },
      { id: "issue", label: "问题与需要支持", group: "问题跟进", required: false, enabled: true, copyToWechat: true },
    ],
  },
  reports: [
    {
      id: 101,
      storeName: "西湖店",
      date: "2026-09-29",
      reporter: "林晓",
      revenue: 6820.5,
      traffic: 176,
      avgTicket: 38.6,
      wasteAmount: 128.4,
      todayDone: "完成新品试吃陈列和会员回访",
      tomorrowPlan: "优化晚高峰补货动线",
      issue: "晚高峰冷柜补货稍慢",
      issueStatus: "待处理",
      updatedAt: "今天 20:48",
    },
    {
      id: 102,
      storeName: "滨江店",
      date: "2026-09-28",
      reporter: "周宁",
      revenue: 5140.75,
      traffic: 118,
      avgTicket: 42.2,
      wasteAmount: 96.25,
      todayDone: "完成周末排班和烤箱清洁",
      tomorrowPlan: "跟进设备维修，调整早餐陈列",
      issue: "烤箱温控已报修",
      issueStatus: "处理中",
      updatedAt: "昨天 21:12",
    },
    {
      id: 103,
      storeName: "钱江新城店",
      date: "2026-09-28",
      reporter: "陈希",
      revenue: 7348,
      traffic: 194,
      avgTicket: 41.1,
      wasteAmount: 88,
      todayDone: "完成中秋礼盒预售确认",
      tomorrowPlan: "安排大客户提货时段",
      issue: "",
      issueStatus: "已解决",
      updatedAt: "昨天 20:36",
    },
    {
      id: 104,
      storeName: "城西店",
      date: "2026-09-27",
      reporter: "许安",
      revenue: 2680,
      traffic: 74,
      avgTicket: 36.2,
      wasteAmount: 42,
      todayDone: "完成新店试营业动线演练",
      tomorrowPlan: "核对设备进场清单",
      issue: "收银台网络偶发掉线",
      issueStatus: "已解决",
      updatedAt: "09-27 19:40",
    },
  ],
  collaboration: [
    {
      id: 201,
      type: "issue",
      storeName: "西湖店",
      title: "晚高峰冷柜补货稍慢",
      body: "18:00 后试吃和伴手礼同时取货，冷柜补货需要绕行后场，希望运营协助调整动线。",
      status: "待查看",
      author: "林晓",
      createdAt: "2026-09-29 20:48",
      updatedAt: "2026-09-29 20:48",
      replies: [],
    },
    {
      id: 202,
      type: "suggestion",
      storeName: "滨江店",
      title: "建议把周末热销榜放到晨会看板",
      body: "周末新品和可颂经常提前售罄，如果晨会能直接看到上周热销榜，排产会更准确。",
      status: "处理中",
      author: "周宁",
      createdAt: "2026-09-28 08:35",
      updatedAt: "2026-09-28 14:20",
      replies: [
        { id: 301, author: "运营经理", role: "operator", body: "收到，本周五前整理一版晨会看板试运行。", createdAt: "2026-09-28 14:20" },
      ],
    },
    {
      id: 203,
      type: "suggestion",
      storeName: "钱江新城店",
      title: "礼盒提货增加取货时间段",
      body: "中秋礼盒大客户提货集中在 17:00，建议开放 15:00–16:00 的预约时段。",
      status: "已回复",
      author: "陈希",
      createdAt: "2026-09-26 16:12",
      updatedAt: "2026-09-27 09:00",
      replies: [
        { id: 302, author: "管理员", role: "admin", body: "已纳入节日销售安排，感谢反馈。", createdAt: "2026-09-27 09:00" },
      ],
    },
  ],
  retrospectives: [
    { id: 401, storeName: "西湖店", title: "新品试吃转化复盘", body: "试吃点位靠近收银台后，会员咨询明显增加。下次可以把新品卡片和取货动线一起调整。", tags: ["新品", "试吃"], author: "林晓", date: "2026-09-29", mood: "有收获" },
    { id: 402, storeName: "滨江店", title: "周末排班复盘", body: "10:30–12:00 前场压力最高，下一周末将一名后场同事提前 30 分钟转前场。", tags: ["排班", "周末"], author: "周宁", date: "2026-09-28", mood: "需跟进" },
    { id: 403, storeName: "钱江新城店", title: "礼盒预售经验", body: "提前 3 天确认大客户数量，提货日现场会更从容；建议下次沿用清单并增加备用包装。", tags: ["节日", "礼盒"], author: "陈希", date: "2026-09-27", mood: "顺利" },
  ],
  specialDates: [
    { id: 501, date: "2026-09-30", label: "月末会员日", type: "活动日", note: "全店会员储值赠积分，运营关注晚高峰储值转化。", stores: ["全部门店"] },
    { id: 502, date: "2026-10-01", label: "国庆首日", type: "节假日", note: "预计客流上升，提前确认礼盒和伴手礼库存。", stores: ["全部门店"] },
    { id: 503, date: "2026-10-03", label: "礼盒特别销售", type: "特别销售", note: "钱江新城店安排大客户集中提货，15:00–18:00 增加一名前场。", stores: ["钱江新城店"] },
    { id: 504, date: "2026-10-06", label: "秋季新品首发", type: "特别销售", note: "西湖店、滨江店同步新品试吃，日报需记录试吃转化。", stores: ["西湖店", "滨江店"] },
  ],
  auditLogs: [
    { id: 601, action: "更新建议状态", actor: "运营经理", role: "operator", target: "建议 #202", detail: "待查看 → 处理中", createdAt: "2026-09-28 14:20" },
    { id: 602, action: "编辑日报模板", actor: "管理员", role: "admin", target: "标准版", detail: "启用字段：问题与需要支持", createdAt: "2026-09-27 18:40" },
    { id: 603, action: "提交日报", actor: "林晓", role: "store", target: "西湖店 · 2026-09-29", detail: "实收 ¥6,820.50", createdAt: "2026-09-29 20:48" },
    { id: 604, action: "新增日历标注", actor: "运营经理", role: "operator", target: "2026-10-06", detail: "秋季新品首发", createdAt: "2026-09-27 10:12" },
  ],
};
