import { motion } from "framer-motion";
import {
  Activity,
  ArrowUpRight,
  CalendarPlus,
  Check,
  CircleAlert,
  Clock3,
  MessageCircle,
  MoreHorizontal,
  NotebookPen,
  Send,
  Sparkles,
  Tag,
  UsersRound,
} from "lucide-react";
import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from "react";
import { useAuth } from "../_core/hooks/useAuth";
import { trpc } from "../lib/trpc";
import type { AppData, CollaborationItem, Retrospective, WorkspaceView } from "../types";
import { Button, CalendarView, Card, Drawer, EmptyState, Field, SearchField, SectionHeader, StatCard, StatusPill, Textarea } from "../components/UiKit";

const money = (value: number) => `¥${value.toLocaleString("zh-CN", { maximumFractionDigits: 0 })}`;
const statusTone = (value: string) => value === "已回复" || value === "已解决" ? "green" : value === "处理中" ? "blue" : "orange";

export default function OperationsWorkspace({ data, view, onChange, onFlash, sessionName, onNavigate }: { data: AppData; view: WorkspaceView; onChange: Dispatch<SetStateAction<AppData>>; onFlash: (message: string) => void; sessionName: string; onNavigate: (view: WorkspaceView) => void }) {
  const auth = useAuth();
  const remoteMe = trpc.workspace.me.useQuery(undefined, { enabled: auth.isAuthenticated, retry: false });
  const remoteCollaboration = trpc.workspace.listCollaboration.useQuery({}, { enabled: Boolean(remoteMe.data && remoteMe.data.role !== "store"), retry: false });
  const remoteRetrospectives = trpc.workspace.listRetrospectives.useQuery({}, { enabled: Boolean(remoteMe.data && remoteMe.data.role !== "store"), retry: false });
  const replyRemote = trpc.workspace.replyCollaboration.useMutation();
  const statusRemote = trpc.workspace.updateCollaborationStatus.useMutation();
  const createRemoteRetro = trpc.workspace.createRetrospective.useMutation();
  const [panel, setPanelState] = useState<WorkspaceView>(view);
  useEffect(() => setPanelState(view), [view]);
  const setPanel = (next: WorkspaceView) => { setPanelState(next); onNavigate(next); };
  const [query, setQuery] = useState("");
  const [selectedThread, setSelectedThread] = useState<CollaborationItem | null>(null);
  const [reply, setReply] = useState("");
  const [selectedDate, setSelectedDate] = useState("2026-10-01");
  const [showEventForm, setShowEventForm] = useState(false);
  const [eventDraft, setEventDraft] = useState({ label: "", type: "活动日" as "节假日" | "活动日" | "特别销售", note: "", stores: "全部门店" });
  const [retroTitle, setRetroTitle] = useState("");
  const [retroBody, setRetroBody] = useState("");
  const [retroTags, setRetroTags] = useState("");
  const remoteRole = remoteMe.data?.role;
  useEffect(() => { if (!remoteCollaboration.data) return; onChange(current => ({ ...current, collaboration: remoteCollaboration.data.map(item => ({ id: item.id, type: item.type, storeName: item.storeName, title: item.title, body: item.content, status: item.status, author: item.authorName, createdAt: item.createdAt instanceof Date ? item.createdAt.toISOString() : String(item.createdAt), updatedAt: item.updatedAt instanceof Date ? item.updatedAt.toISOString() : String(item.updatedAt), replies: item.replies.map(reply => ({ id: reply.id, author: reply.authorName, role: reply.authorRole, body: reply.body, createdAt: reply.createdAt instanceof Date ? reply.createdAt.toISOString() : String(reply.createdAt) })) })) })); }, [remoteCollaboration.data, onChange]);
  useEffect(() => { if (!remoteRetrospectives.data) return; onChange(current => ({ ...current, retrospectives: remoteRetrospectives.data.map(item => ({ id: item.id, storeName: item.storeName, title: item.title, body: item.body, tags: item.tags, author: item.authorName, date: item.retroDate, mood: item.mood })) })); }, [remoteRetrospectives.data, onChange]);
  const visibleItems = useMemo(() => data.collaboration.filter(item => `${item.storeName}${item.title}${item.body}`.toLowerCase().includes(query.toLowerCase())), [data.collaboration, query]);
  const visibleReports = data.reports.filter(item => item.date >= "2026-09-23");
  const todayRevenue = visibleReports.filter(item => item.date === "2026-09-29").reduce((sum, item) => sum + item.revenue, 0);
  const unresolved = data.collaboration.filter(item => item.status === "待查看" || item.status === "处理中").length;
  const addAudit = (action: string, target: string, detail: string) => onChange(current => ({ ...current, auditLogs: [{ id: Date.now(), action, actor: sessionName, role: "operator", target, detail, createdAt: "刚刚" }, ...current.auditLogs] }));
  const sendReply = async () => { if (!selectedThread || !reply.trim()) return; const itemId = selectedThread.id; if (remoteRole === "admin" || remoteRole === "operator") { try { await replyRemote.mutateAsync({ itemId, body: reply.trim() }); } catch (error) { onFlash(error instanceof Error ? error.message : "回复同步失败"); return; } } const nextReply = { id: Date.now(), author: sessionName, role: "operator" as const, body: reply.trim(), createdAt: "刚刚" }; onChange(current => ({ ...current, collaboration: current.collaboration.map(item => item.id === itemId ? { ...item, status: item.type === "issue" ? "处理中" : "已回复", updatedAt: "刚刚", replies: [...item.replies, nextReply] } : item) })); addAudit("回复协作事项", `#${itemId} · ${selectedThread.title}`, reply.trim()); setSelectedThread(null); setReply(""); onFlash(remoteRole ? "回复已记录并同步服务端" : "回复已记录，店长端会同步看到"); };
  const updateStatus = async (item: CollaborationItem, status: CollaborationItem["status"]) => { if (remoteRole === "admin" || remoteRole === "operator") { try { await statusRemote.mutateAsync({ itemId: item.id, status }); } catch (error) { onFlash(error instanceof Error ? error.message : "状态同步失败"); return; } } onChange(current => ({ ...current, collaboration: current.collaboration.map(row => row.id === item.id ? { ...row, status, updatedAt: "刚刚" } : row) })); addAudit("更新事项状态", `#${item.id} · ${item.title}`, `${item.status} → ${status}`); onFlash(remoteRole ? `已标记为${status}并同步服务端` : `已标记为${status}`); };
  const addEvent = () => { if (!eventDraft.label.trim()) return; const event = { id: Date.now(), date: selectedDate, label: eventDraft.label.trim(), type: eventDraft.type, note: eventDraft.note.trim(), stores: [eventDraft.stores] }; onChange(current => ({ ...current, specialDates: [...current.specialDates, event] })); addAudit("新增日历标注", selectedDate, eventDraft.label.trim()); setEventDraft({ label: "", type: "活动日", note: "", stores: "全部门店" }); setShowEventForm(false); onFlash("日历标注已同步"); };
  const saveRetro = async () => { if (!retroTitle.trim() || !retroBody.trim()) return; const tags = retroTags.split(/[、,，\s]+/).filter(Boolean).slice(0, 4); if (remoteRole === "admin" || remoteRole === "operator") { try { await createRemoteRetro.mutateAsync({ storeName: "全门店", title: retroTitle.trim(), body: retroBody.trim(), tags, retroDate: "2026-09-29", mood: "有收获" }); } catch (error) { onFlash(error instanceof Error ? error.message : "复盘同步失败"); return; } } const retro: Retrospective = { id: Date.now(), storeName: "全门店", title: retroTitle.trim(), body: retroBody.trim(), tags, author: sessionName, date: "2026-09-29", mood: "有收获" }; onChange(current => ({ ...current, retrospectives: [retro, ...current.retrospectives] })); addAudit("新增复盘备忘", retro.title, retro.tags.join(" / ")); setRetroTitle(""); setRetroBody(""); setRetroTags(""); onFlash(remoteRole ? "复盘备忘已保存并同步服务端" : "复盘备忘已保存"); };
  return <div className="workspace-stack"><SectionHeader eyebrow="OPERATIONS DESK" title={panel === "overview" ? "运营总览" : panel === "reports" ? "日报中心" : panel === "collaboration" ? "协作收件箱" : panel === "calendar" ? "运营日历" : "复盘备忘录"} description={panel === "overview" ? "今天先处理最需要团队回应的事情，再把经验留给下一次。" : panel === "calendar" ? "把节日、活动和特别销售变成所有门店都看得见的节奏。" : "跨门店的信息，在这里形成可追踪的处理链路。"} action={<div className="header-actions"><StatusPill label={`${unresolved} 项待跟进`} tone={unresolved ? "orange" : "green"} />{panel === "calendar" && <Button variant="secondary" size="sm" icon={<CalendarPlus size={15} />} onClick={() => setShowEventForm(true)}>新建标注</Button>}{panel === "retrospectives" && <Button variant="secondary" size="sm" icon={<NotebookPen size={15} />} onClick={() => document.getElementById("retro-composer")?.scrollIntoView({ behavior: "smooth" })}>写一条复盘</Button>}</div>} />
    {panel === "overview" && <OpsOverview data={data} todayRevenue={todayRevenue} unresolved={unresolved} onPanel={setPanel} onOpen={item => setSelectedThread(item)} />}
    {panel === "reports" && <ReportCenter data={data} query={query} setQuery={setQuery} onFlash={onFlash} />}
    {panel === "collaboration" && <Inbox data={data} items={visibleItems} onOpen={setSelectedThread} onStatus={updateStatus} />}
    {panel === "calendar" && <OpsCalendar data={data} selectedDate={selectedDate} setSelectedDate={setSelectedDate} showEventForm={showEventForm} setShowEventForm={setShowEventForm} eventDraft={eventDraft} setEventDraft={setEventDraft} addEvent={addEvent} />}
    {panel === "retrospectives" && <RetroDesk data={data} query={query} setQuery={setQuery} title={retroTitle} setTitle={setRetroTitle} body={retroBody} setBody={setRetroBody} tags={retroTags} setTags={setRetroTags} saveRetro={saveRetro} />}
    <Drawer open={!!selectedThread} onClose={() => { setSelectedThread(null); setReply(""); }} title={selectedThread?.title || "协作详情"} description={selectedThread ? `${selectedThread.storeName} · ${selectedThread.type === "issue" ? "问题" : "建议"} · ${selectedThread.author}` : ""} footer={selectedThread && <div className="drawer-footer-actions"><Button variant="soft" onClick={() => updateStatus(selectedThread, selectedThread.status === "已解决" ? "处理中" : "已解决")}>{selectedThread.status === "已解决" ? "重新打开" : "标记已解决"}</Button><Button onClick={sendReply} icon={<Send size={15} />}>发送回复</Button></div>}>
      {selectedThread && <div className="thread-detail"><div className="thread-detail-meta"><StatusPill label={selectedThread.status} tone={statusTone(selectedThread.status) as "green" | "blue" | "orange"} /><span>{selectedThread.createdAt}</span></div><p className="thread-body">{selectedThread.body}</p><div className="reply-timeline">{selectedThread.replies.map(item => <div className="reply-item" key={item.id}><div className="avatar avatar-blue">{item.author.slice(0, 1)}</div><div><strong>{item.author}</strong><span>{item.createdAt}</span><p>{item.body}</p></div></div>)}{!selectedThread.replies.length && <div className="timeline-empty">还没有处理记录，从这里留下第一条回应。</div>}</div><div className="reply-composer"><span className="eyebrow">ADD A NOTE</span><Textarea value={reply} onChange={setReply} placeholder="写下处理进展、需要协同的人或下一步动作…" rows={4} /></div></div>}
    </Drawer>
  </div>;
}

function OpsOverview({ data, todayRevenue, unresolved, onPanel, onOpen }: { data: AppData; todayRevenue: number; unresolved: number; onPanel: (panel: WorkspaceView) => void; onOpen: (item: CollaborationItem) => void }) { const urgent = data.collaboration.filter(item => item.status === "待查看" || item.status === "处理中").slice(0, 3); return <><div className="stat-grid"><StatCard label="今日实收" value={money(todayRevenue)} hint="来自已提交日报" icon={<Activity size={19} />} tone="orange" /><StatCard label="待跟进" value={String(unresolved)} hint="建议与问题" icon={<CircleAlert size={19} />} tone="gold" /><StatCard label="本周日报" value={String(data.reports.length)} hint="全部门店" icon={<ClipboardMini />} tone="blue" /><StatCard label="复盘备忘" value={String(data.retrospectives.length)} hint="持续沉淀" icon={<NotebookPen size={19} />} tone="green" /></div><div className="two-column-grid"><Card className="priority-card"><div className="card-heading"><div><span className="eyebrow">YOUR NEXT MOVES</span><h3>优先处理</h3></div><Button variant="ghost" size="sm" onClick={() => onPanel("collaboration")}>查看收件箱 <ArrowUpRight size={14} /></Button></div><div className="priority-list">{urgent.map((item, index) => <motion.button layout key={item.id} onClick={() => onOpen(item)} className="priority-row"><span className="priority-index">0{index + 1}</span><div className="priority-copy"><strong>{item.title}</strong><span>{item.storeName} · {item.type === "issue" ? "问题" : "建议"}</span></div><StatusPill label={item.status} tone={statusTone(item.status) as "green" | "blue" | "orange"} /><ArrowUpRight size={15} /></motion.button>)}{!urgent.length && <EmptyState icon={<Check size={21} />} title="今天的收件箱很安静" description="新的事项会出现在这里。" />}</div></Card><Card className="pulse-card"><div className="pulse-visual"><div className="pulse-orbit orbit-one" /><div className="pulse-orbit orbit-two" /><div className="pulse-core"><Sparkles size={25} /></div></div><div><span className="eyebrow">TEAM PULSE</span><h3>门店正在发生什么</h3><p>西湖店今天完成新品试吃，钱江新城店正在准备节日礼盒提货。</p><Button variant="soft" size="sm" onClick={() => onPanel("calendar")}>打开运营日历 <ArrowUpRight size={14} /></Button></div></Card></div><div className="insight-strip insight-blue"><div className="insight-mark">↗</div><div><strong>把“回复过”变成“跟进过”</strong><span>每一次评论都可以变成下一次复盘的线索，别让重要信息停留在聊天记录里。</span></div><div className="insight-stat"><b>{data.collaboration.reduce((sum, item) => sum + item.replies.length, 0)}</b><span>条处理记录</span></div></div></>; }

function ReportCenter({ data, query, setQuery, onFlash }: { data: AppData; query: string; setQuery: (value: string) => void; onFlash: (message: string) => void }) { const rows = data.reports.filter(item => `${item.storeName}${item.reporter}${item.date}`.toLowerCase().includes(query.toLowerCase())); return <Card className="data-card"><div className="data-toolbar"><div><span className="eyebrow">REPORT STREAM</span><h3>日报中心</h3></div><SearchField value={query} onChange={setQuery} placeholder="搜索门店、填报人或日期" /></div><div className="report-timeline">{rows.map(report => <motion.div layout className="report-timeline-row" key={report.id}><div className="timeline-date"><b>{report.date.slice(8)}</b><span>{report.date.slice(0, 7)}</span></div><div className="timeline-line"><span /></div><div className="report-main"><div className="report-row-head"><div><strong>{report.storeName}</strong><span>{report.reporter} · {report.updatedAt}</span></div>{report.issue ? <StatusPill label={report.issueStatus} tone={statusTone(report.issueStatus) as "green" | "blue" | "orange"} /> : <StatusPill label="正常" tone="green" />}</div><div className="report-metrics"><div><span>实收</span><b>{money(report.revenue)}</b></div><div><span>客流</span><b>{report.traffic}</b></div><div><span>客单价</span><b>¥{report.avgTicket}</b></div><div><span>报损</span><b>¥{report.wasteAmount}</b></div></div>{report.issue && <div className="report-issue"><CircleAlert size={14} /><span>{report.issue}</span></div>}</div><Button variant="ghost" size="sm" onClick={() => onFlash("日报详情抽屉已准备")}>查看 <ArrowUpRight size={14} /></Button></motion.div>)}</div></Card>; }

function Inbox({ data, items, onOpen, onStatus }: { data: AppData; items: CollaborationItem[]; onOpen: (item: CollaborationItem) => void; onStatus: (item: CollaborationItem, status: CollaborationItem["status"]) => void }) { return <div className="inbox-layout"><Card className="inbox-list-card"><div className="card-heading"><div><span className="eyebrow">INBOX</span><h3>需要回应的事</h3></div><StatusPill label={`${items.length} 条`} tone="orange" /></div><div className="inbox-list">{items.map(item => <button className="inbox-row" key={item.id} onClick={() => onOpen(item)}><div className={`inbox-type inbox-${item.type}`}>{item.type === "issue" ? "!" : "↗"}</div><div className="inbox-copy"><div><strong>{item.title}</strong><span>{item.storeName}</span></div><p>{item.body}</p><small>{item.replies.length ? `${item.replies.length} 条处理记录` : "等待第一条处理记录"} · {item.updatedAt}</small></div><StatusPill label={item.status} tone={statusTone(item.status) as "green" | "blue" | "orange"} /></button>)}{!items.length && <EmptyState title="没有匹配事项" description="换一个关键词试试。" />}</div></Card><Card className="inbox-summary"><div className="card-heading"><div><span className="eyebrow">WORKFLOW</span><h3>处理节奏</h3></div><MoreHorizontal size={18} /></div><div className="workflow-stages"><div><b>{data.collaboration.filter(item => item.status === "待查看").length}</b><span>待查看</span></div><div><b>{data.collaboration.filter(item => item.status === "处理中").length}</b><span>处理中</span></div><div><b>{data.collaboration.filter(item => item.status === "已回复" || item.status === "已解决").length}</b><span>已完成</span></div></div><div className="workflow-bar"><span style={{ width: `${Math.max(12, data.collaboration.filter(item => item.status === "已回复" || item.status === "已解决").length / Math.max(1, data.collaboration.length) * 100)}%` }} /></div><p>回复不只是结束一条消息，而是为下一次复盘留下上下文。</p><Button variant="soft" size="sm" onClick={() => onStatus(items[0], "处理中")} disabled={!items.length}>把第一条标记为处理中</Button></Card></div>; }

function OpsCalendar({ data, selectedDate, setSelectedDate, showEventForm, setShowEventForm, eventDraft, setEventDraft, addEvent }: { data: AppData; selectedDate: string; setSelectedDate: (date: string) => void; showEventForm: boolean; setShowEventForm: (value: boolean) => void; eventDraft: { label: string; type: "节假日" | "活动日" | "特别销售"; note: string; stores: string }; setEventDraft: (value: typeof eventDraft) => void; addEvent: () => void }) { const events = data.specialDates.filter(item => item.date === selectedDate); return <div className="calendar-layout"><Card><CalendarView events={data.specialDates} selectedDate={selectedDate} onSelect={setSelectedDate} editable onAdd={date => { setSelectedDate(date); setShowEventForm(true); }} /></Card><Card className="calendar-detail"><div className="card-heading"><div><span className="eyebrow">OPERATIONS NOTE</span><h3>{selectedDate} 的安排</h3></div><Button variant="soft" size="sm" icon={<CalendarPlus size={14} />} onClick={() => setShowEventForm(true)}>添加标注</Button></div>{events.length ? <div className="event-detail-list">{events.map(event => <div className="event-detail" key={event.id}><div className="event-type-dot" /><div><strong>{event.label}</strong><span>{event.type} · {event.stores.join("、")}</span><p>{event.note}</p></div></div>)}</div> : <EmptyState icon={<Clock3 size={21} />} title="这一天还没有安排" description="把销售节奏、节日提醒或门店协同写下来。" />}{showEventForm && <div className="inline-form"><div className="form-title"><strong>创建运营标注</strong><button onClick={() => setShowEventForm(false)}>关闭</button></div><Field label="标题"><input value={eventDraft.label} onChange={e => setEventDraft({ ...eventDraft, label: e.target.value })} placeholder="例如：新品首发" /></Field><Field label="类型"><select value={eventDraft.type} onChange={e => setEventDraft({ ...eventDraft, type: e.target.value as typeof eventDraft.type })}><option>节假日</option><option>活动日</option><option>特别销售</option></select></Field><Field label="关联门店"><select value={eventDraft.stores} onChange={e => setEventDraft({ ...eventDraft, stores: e.target.value })}><option>全部门店</option>{data.stores.map(store => <option key={store}>{store}</option>)}</select></Field><Field label="备注"><textarea rows={3} value={eventDraft.note} onChange={e => setEventDraft({ ...eventDraft, note: e.target.value })} placeholder="这一天需要团队注意什么？" /></Field><Button onClick={addEvent} icon={<Check size={15} />}>保存日历标注</Button></div>}</Card></div>; }

function RetroDesk({ data, query, setQuery, title, setTitle, body, setBody, tags, setTags, saveRetro }: { data: AppData; query: string; setQuery: (value: string) => void; title: string; setTitle: (value: string) => void; body: string; setBody: (value: string) => void; tags: string; setTags: (value: string) => void; saveRetro: () => void }) { const rows = data.retrospectives.filter(item => `${item.title}${item.body}${item.tags.join("")}${item.storeName}`.toLowerCase().includes(query.toLowerCase())); return <div className="retro-layout"><Card className="retro-composer" id="retro-composer"><div className="card-heading"><div><span className="eyebrow">LEAVE A TRACE</span><h3>写下今天的复盘</h3></div><NotebookPen size={20} /></div><p className="card-lead">复盘不需要长篇大论，只要留下下次能用上的一个判断。</p><Field label="标题"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="例如：周末排班复盘" /></Field><Field label="内容"><Textarea value={body} onChange={setBody} placeholder="发生了什么？下次会怎么做？" rows={7} /></Field><Field label="标签"><input value={tags} onChange={e => setTags(e.target.value)} placeholder="用空格或逗号分隔，例如：排班 周末" /></Field><Button onClick={saveRetro} icon={<NotebookPen size={15} />}>保存为备忘</Button></Card><Card className="retro-list-card"><div className="card-heading"><div><span className="eyebrow">MEMORY BANK</span><h3>团队复盘</h3></div><SearchField value={query} onChange={setQuery} placeholder="搜索关键词" /></div><div className="retro-list">{rows.map(item => <motion.article layout className="retro-note" key={item.id}><div className="retro-note-top"><div className="retro-date"><b>{item.date.slice(8)}</b><span>{item.date.slice(0, 7)}</span></div><StatusPill label={item.mood} tone={item.mood === "顺利" ? "green" : item.mood === "有收获" ? "blue" : "orange"} /></div><h4>{item.title}</h4><p>{item.body}</p><div className="tag-row">{item.tags.map(tag => <span key={tag}><Tag size={12} />{tag}</span>)}</div><footer>{item.storeName} · {item.author}</footer></motion.article>)}{!rows.length && <EmptyState title="还没有这类复盘" description="换个关键词或从左侧写下一条。" />}</div></Card></div>; }
function ClipboardMini() { return <div className="clipboard-mini"><span /></div>; }
